# Enable all debug helpers
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2
CONFIG_ASSERT_VERBOSE=y
CONFIG_INIT_STACKS=y

# Configure logging
CONFIG_LOG=y
CONFIG_LOG_INFO_COLOR_GREEN=y
CONFIG_LOG_DBG_COLOR_BLUE=y
CONFIG_LOG_TIMESTAMP_64BIT=y
CONFIG_LOG_OUTPUT_FORMAT_LINUX_TIMESTAMP=y

# Enable shell
CONFIG_SHELL=y

# Configure heap memory
CONFIG_HEAP_MEM_POOL_SIZE=180000

# Enable and configure CMSIS-RTOS v2 compatibility layer
CONFIG_CMSIS_RTOS_V2=y
CONFIG_CMSIS_V2_THREAD_MAX_STACK_SIZE=1024
CONFIG_CMSIS_V2_THREAD_DYNAMIC_STACK_SIZE=1024
CONFIG_CMSIS_V2_THREAD_DYNAMIC_MAX_COUNT=8
CONFIG_CMSIS_V2_MEM_SLAB_MAX_DYNAMIC_SIZE=8096
CONFIG_CMSIS_V2_MSGQ_MAX_DYNAMIC_SIZE=1024

# Configure multithreading
CONFIG_NUM_PREEMPT_PRIORITIES=56
CONFIG_MULTITHREADING=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_STACK_INFO=y

# Enable SRTP2 stack
CONFIG_SRTP2=y

# Enable GPIOs
CONFIG_GPIO=y

# Enable L2 (Ethernet) networking.
CONFIG_NETWORKING=y
CONFIG_NET_NATIVE=y
CONFIG_NET_DRIVERS=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_PACKET=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_STM32_RNG=y

# Enable input drivers and nunchuck
CONFIG_INPUT=y
CONFIG_INPUT_MODE_SYNCHRONOUS=y
CONFIG_INPUT_NUNCHUKNG=y

# Enable clock API.
CONFIG_POSIX_TIMERS=y
