#pragma once

/* Frame* */
enum {
    FRAME_DESTINATION_ADDRESS_OFFSET = 0,
    FRAME_DESTINATION_ADDRESS_LENGTH = 6,

    FRAME_SOURCE_ADDRESS_OFFSET = FRAME_DESTINATION_ADDRESS_OFFSET + FRAME_DESTINATION_ADDRESS_LENGTH,
    FRAME_SOURCE_ADDRESS_LENGTH = 6,

    FRAME_ETHERTYPE_OFFSET = FRAME_SOURCE_ADDRESS_OFFSET + FRAME_SOURCE_ADDRESS_LENGTH,
    FRAME_ETHERTYPE_LENGTH = 2
};

/* SRTP2 */
enum {
    SRTP_ETHERTYPE = 0xDCAC, // Network byte order!

    SRTP2_TYPE_OFFSET = FRAME_ETHERTYPE_OFFSET + FRAME_ETHERTYPE_LENGTH,
    SRTP2_TYPE_LENGTH = 1,
};

/* SRTP2 Beacon */
enum {
    SRTP2_TYPE_BEACON = 0x00,

    SRTP2_BEACON_NETWORK_ID_OFFSET = SRTP2_TYPE_OFFSET + SRTP2_TYPE_LENGTH,
    SRTP2_BEACON_NETWORK_ID_SIZE = 32,

    SRTP2_BEACON_NETWORK_TIME_OFFSET = SRTP2_BEACON_NETWORK_ID_OFFSET + SRTP2_BEACON_NETWORK_ID_SIZE,
    SRTP2_BEACON_NETWORK_TIME_LENGTH = 8,

    SRTP2_BEACON_CYCLE_INTERVAL_OFFSET = SRTP2_BEACON_NETWORK_TIME_OFFSET + SRTP2_BEACON_NETWORK_TIME_LENGTH,
    SRTP2_BEACON_CYCLE_INTERVAL_LENGTH = 4,

    SRTP2_BEACON_SV_GROUP_MASK_OFFSET = SRTP2_BEACON_CYCLE_INTERVAL_OFFSET + SRTP2_BEACON_CYCLE_INTERVAL_LENGTH,
    SRTP2_BEACON_SV_GROUP_MASK_LENGTH = 4,

    SRTP2_BEACON_LENGTH = SRTP2_BEACON_SV_GROUP_MASK_OFFSET + SRTP2_BEACON_SV_GROUP_MASK_LENGTH
};

/* SRTP2 MPDU */
enum {
    SRTP2_TYPE_MPDU = 0x01,

    SRTP2_MPDU_EPDU_COUNT_OFFSET = SRTP2_TYPE_OFFSET + SRTP2_TYPE_LENGTH,
    SRTP2_MPDU_EPDU_COUNT_LENGTH = 2,

    SRTP2_MPDU_PAYLOAD_OFFSET = SRTP2_MPDU_EPDU_COUNT_OFFSET + SRTP2_MPDU_EPDU_COUNT_LENGTH,
    SRTP2_MPDU_MINIMAL_LENGHT = SRTP2_MPDU_PAYLOAD_OFFSET
};

/* SRTP2 ePDU */
enum {
    SRTP2_EPDU_TYPE_OFFSET = 0,
    SRTP2_EPDU_TYPE_LENGTH = 1
};

/* SRTP2 SV ePDU */
enum {
    SRTP2_EPDU_TYPE_SAMPLED_VALUE = 0x00,

    SRTP2_SV_EPDU_SVGROUP_OFFSET = SRTP2_EPDU_TYPE_OFFSET + SRTP2_EPDU_TYPE_LENGTH,
    SRTP2_SV_EPDU_SVGROUP_LENGTH = 1,

    SRTP2_SV_EPDU_LENGTH_OFFSET = SRTP2_SV_EPDU_SVGROUP_OFFSET + SRTP2_SV_EPDU_SVGROUP_LENGTH,
    SRTP2_SV_EPDU_LENGTH_LENGTH = 2,

    SRTP2_SV_EPDU_PAYLOAD_OFFSET = SRTP2_SV_EPDU_LENGTH_OFFSET + SRTP2_SV_EPDU_LENGTH_LENGTH,
};

/* SRTP2 EV ePDU */
enum {
    SRTP2_EPDU_TYPE_EVENT = 0x01,

    SRTP2_EV_EPDU_EVENTID_OFFSET = SRTP2_EPDU_TYPE_OFFSET + SRTP2_EPDU_TYPE_LENGTH,
    SRTP2_EV_EPDU_EVENTID_LENGTH = 2,

    SRTP2_EV_EPDU_TIMESTAMP_OFFSET = SRTP2_EV_EPDU_EVENTID_OFFSET + SRTP2_EV_EPDU_EVENTID_LENGTH,
    SRTP2_EV_EPDU_TIMESTAMP_LENGTH = 8,

    SRTP2_EV_EPDU_LENGHT_OFFSET = SRTP2_EV_EPDU_TIMESTAMP_OFFSET + SRTP2_EV_EPDU_TIMESTAMP_LENGTH,
    SRTP2_EV_EPDU_LENGHT_LENGTH = 2,

    SRTP2_EV_EPDU_PAYLOAD_OFFSET = SRTP2_EV_EPDU_LENGHT_OFFSET + SRTP2_EV_EPDU_LENGHT_LENGTH
};

/* SRTP2 MSG ePDU */
enum {
     SRTP2_EPDU_TYPE_MESSAGE = 0x02,
    SRTP2_MSG_EPDU_DESTINATION_ADDRESS_OFFSET = SRTP2_EPDU_TYPE_OFFSET + SRTP2_EPDU_TYPE_LENGTH,
    SRTP2_MSG_EPDU_DESTINATION_ADDRESS_LENGTH = 6,

    SRTP2_MSG_EPDU_DESTINATION_SAPI_OFFSET = SRTP2_MSG_EPDU_DESTINATION_ADDRESS_OFFSET + SRTP2_MSG_EPDU_DESTINATION_ADDRESS_LENGTH,
    SRTP2_MSG_EPDU_DESTINATION_SAPI_LENGTH = 2,

    SRTP2_MSG_EPDU_SOURCE_SAPI_OFFSET = SRTP2_MSG_EPDU_DESTINATION_SAPI_OFFSET + SRTP2_MSG_EPDU_DESTINATION_SAPI_LENGTH,
    SRTP2_MSG_EPDU_SOURCE_SAPI_LENGTH = 2,

    SRTP2_MSG_EPDU_FLAGS_OFFSET = SRTP2_MSG_EPDU_SOURCE_SAPI_OFFSET + SRTP2_MSG_EPDU_SOURCE_SAPI_LENGTH,
    SRTP2_MSG_EPDU_FLAGS_LENGTH = 1,

     SRTP2_MSG_EPDU_FLAGS_LAST_FRAGMENT = 1 << 0,

    SRTP2_MSG_EPDU_LENGTH_OFFSET = SRTP2_MSG_EPDU_FLAGS_OFFSET + SRTP2_MSG_EPDU_FLAGS_LENGTH,
    SRTP2_MSG_EPDU_LENGTH_LENGTH = 2,

    SRTP2_MSG_EPDU_PAYLOAD_OFFSET = SRTP2_MSG_EPDU_LENGTH_OFFSET + SRTP2_MSG_EPDU_LENGTH_LENGTH
};
